project:
  type: website

website:
  title: "CANARY TOURS.KE"
  description: "A tours and travel agency offering team activities and hotel bookings"
  back-to-top-navigation: true
  
  favicon: "./pages/images/logo.jpg"
  twitter-card: true
  site-url: https://canarytourske.onrender.com/
  
  search: 
    location: navbar
    type: textbox
  
  page-footer: 
    left: "Created by: Kwiz Computing Technologies Limited" 
    right: "Copyright: Canary Tours.ke (2023)"
    center: 
      - icon: github
        href: https://github.com/Kwiz-Computing-Technologies-Limited/Canary_ToursKE/blob/main
        target: _blank
      - icon: twitter 
        href: https://twitter.com/ 
        target: _blank
      - icon: instagram
        href: https://instagram.com/
        target: _blank
      - icon: tiktok
        href: https://tiktok.com/
        target: _blank
      - icon: facebook
        href: https://facebook.com/
        target: _blank
      - icon: whatsapp
        href: https://chat.whatsapp.com/D6QKPzWip0HGCPf8P3Z5Yb
        target: _blank
      - icon: email
        href: mailto:kanjabrian955@gmail.com
        target: _blank


  navbar:
    logo: "./pages/images/logo.jpeg"
    logo-alt: "My Logo"

    right:
      - text: "Home"
        href: index.html


format:
  html:
    page-layout: full
    css: styles.css
    toc: false
    toc-location: right
    toc-title: " "
    theme: 
      light: simplex
      dark: darkly


    highlight: tango
    toc_float: true
    