project:
  type: website

website:
  title: "CANARY TOURS.KE"
  description: "A tours and travel agency offering team activities and hotel bookings"
  back-to-top-navigation: true
  
  favicon: "./pages/images/logo.jpg"
  twitter-card: true
  site-url: https://canarytourske.onrender.com/
  
  search: 
    location: navbar
    type: textbox
  
  page-footer: 
    left: "Created by: Kwiz Computing Technologies Limited" 
    right: "Copyright: Canary Tours.ke (2023)"
    center: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 
      - icon: instagram
        href: https://instagram.com/
      - icon: tiktok
        href: https://tiktok.com/
      - icon: facebook
        href: https://facebook.com/
      - icon: whatsapp
        href: https://chat.whatsapp.com/D6QKPzWip0HGCPf8P3Z5Yb
      - icon: email
      

  navbar:
    logo: "./pages/images/logo.jpg"
    logo-alt: "My Logo"

    right:
      - text: "Home"
        href: index.html
          # Add more services here...
      - text: "Hotel bookings"
        href: pages/hotel_bookings.html
      - text: "Travel Magazine"
        href: pages/travel_magazine.html
      - text: "About Us"
        href: pages/about.html


format:
  html:
    page-layout: full
    css: styles.css
    toc: true
    toc-location: right
    theme: 
      light: morph
      dark: solar


    highlight: tango
    toc_float: true
    