project:
  type: website

website:
  title: "CANARY TOURS.KE"
  description: "A tours and travel agency offering team activities and hotel bookings"
  back-to-top-navigation: true
  
  search: 
    location: navbar
    type: textbox
  
  page-footer: 
    left: "Created by: Kwiz Computing Technologies Limited" 
    right: "Copyright: Canary Tours.ke (2023)"
    center: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 
      - icon: instagram
        href: https://instagram.com/
      - icon: tiktok
        href: https://tiktok.com/
      - icon: facebook
        href: https://facebook.com/
      - icon: whatsapp
        href: https://whatsapp.com/

  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Deals!"
        menu:
          - text: "Game drives"
            href: pages/game_drives.html
          - text: "Picnics"
            href: pages/picnics.html
          - text: "Ziplining"
            href: pages/Ziplining.html
          - text: "Camping"
            href: pages/Camping.html
          - text: "Car Leasing"
            href: pages/Car_leasing.html
          - text: "Corporate Activities"
            href: pages/Corporates.html
          - text: "Cultural Adventures"
            href: pages/Cultural_Adventure.html
          - text: "Destinations"
            href: pages/Destinations.html
          - text: "Rock Climbing"
            href: pages/Rock_climbing.html
          - text: "Safari"
            href: pages/Safari.html
          - text: "Team Building"
            href: pages/Team_building.html
          - text: "Festivals & Events"
            href: pages/Festival_Events.html
          - text: "Hiking & Trekking"
            href: pages/Hiking_Trekking.html
          
          # Add more services here...
      - text: "Hotel bookings"
        href: pages/hotel_bookings.html
      - text: "Travel Magazine"
        href: pages/travel_magazine.html
      - text: "About Us"
        href: pages/about.html


format:
  html:
    page-layout: full
    css: styles.css
    toc: true
    theme: united
    highlight: tango
    toc_float: true
    