---
site:
  output: html
  theme: quarto
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
source("./pages/functions/sliding_cards.R")
```

```{r libraries, echo=FALSE, message=FALSE, warning=FALSE}
library(htmltools)
library(bslib)
```

```{r styling, echo=FALSE, message=FALSE, warning=FALSE}
# Add some custom CSS styling to the cards
tags$style("
  .title {
    color: grey90;
    font-size: 30px;
  }
  
  h1 {
    font-size: 30px;
    text-align: center;
  }


  a {
    text-decoration: none;
    font-size: 30px;
    color: brown;
  }

  button:hover, a:hover {
    opacity: 0.7;
  }
  
  /* Style the card container */
  .card {
    box-shadow: 0px 0px 0px 0px;
    max-width: 100%;
    max-height:auto;
    margin: auto;
    text-align: center;
    font-family: arial;
    border-radius: 10px;
    overflow: hidden;
    border-top: 2px solid rgba(143, 151, 121, 0.5);
    background: rgba(246, 215, 176, 0.1)
  }

  /* Style the card header */
  .card-header {
    padding: 10px;
    background-color: inherit;
    color: inverse;
    text-align: center;
    font-family: arial;
    font-size: 30px;
    font-weight: bold;
    border-bottom: 2px solid rgba(143, 151, 121, 0.8);
  }

  /* Style the card image */
  .card-image {
    width: 100%;
    object-fit: cover;
    border-radius: 10px;
  }

  /* Style the card text */
  .card-text {
    color: grey90;
    font-size: 30px;
  }
  
  /* Style button*/
  button {
    outline: 0;
    display: inline-block;
    padding: 8px;
    text-align: center;
    cursor: pointer;
    max-width: 60%;
    font-size: 30px;
    border-radius: 10px;
    border: none;
    border-bottom: 2px solid rgba(143, 151, 121, 1);
    url: https://chat.whatsapp.com/D6QKPzWip0HGCPf8P3Z5Yb;
    margin-left: 20%;
    margin-right: 20%;
  }
  
  /* Container holding the image and the text */
  .container {
    position: relative;
    text-align: center;
    color: inherit;
    object-fit: fill;
    max-width: 100%;
    max-height:auto;
    margin: auto;
  }

  /* Top left text */
  .top-left {
    position: relative;
    max-top: 100px;
    max-left: 205px;
    max-right: 200px;
    min-bottom: 100px;
    color: grey90;
    font-size: 30px;
    background-color: inherit;
    opacity: 0.8;
    border-radius: 10px;
  }
")
```


```{r Landingpage, echo=FALSE, message=FALSE, warning=FALSE}
# Define Landing_page Card
card_images <- function(i) {
  src = paste0("./pages/images/image", i, ".jpg")
  
  list(
    header = card_header(
      htmltools::tags$div(
        " ",
        style = "color:brown; font-size:30px; font-color: brown; margin-left: 20%; margin-right: 20%; font-weight: bold;"
      )),
    
    body1 = card_body(
      # Add a div tag for the card text
      htmltools::tags$div(
        class = "container",
        htmltools::tags$image(
          src = src,
          class = "card-image"
          ))),
    
    body2 = card_body(
      
      # Add a div tag for the card text
      htmltools::tags$div(
        class = "card-text",
        "Find places where your dollars go the farthest and tips to create amazing travel experiences without breaking the bank. Travel more and spend less!"),
      
      htmltools::tags$button(
        class = "button",
        htmltools::tags$a(
          href = "https://chat.whatsapp.com/D6QKPzWip0HGCPf8P3Z5Yb",
          "Contact Us",
          
          style = "color: brown;")
        ))
    )
}


cards <- lapply(2:3, function(x) card_images(i = x))
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Render the slideshow
htmltools::browsable(
  tags$html(
    tags$head(
      # Use Bootstrap 5
      tags$link(
        rel = "stylesheet",
        href = "https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
      )
    ),
    
    tags$body(
      slideshow(cards),
      # Add some custom CSS for the animations
      card_animation()
    )
  )
)
```



```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Render the mission and vision cards

mission_vision_card = list(
  # Mission
  list(
    body1 = card_body(
      # Add a div tag for the card text
      htmltools::tags$div(
        "Our Mission",
        style = "color:brown; font-size:30px; font-color: brown; margin-left: 20%; margin-right: 20%; font-weight: bold;")),
    
    body2 = card_body(
      height = "100px",
      
      # Add a div tag for the card text
      htmltools::tags$div(
        "Turning every moment into a lifetime memory",
        class = "title",
        style = "text-align: center;"))
    ),
  
  # Vision
  list(
    body1 = card_body(
      # Add a div tag for the card text
      htmltools::tags$div(
        "Our Vision",
        style = "color:brown; font-size:30px; font-color: brown; margin-left: 20%; margin-right: 20%; font-weight: bold;")),
    
    body2 = card_body(
      height = "100px",
      
      # Add a div tag for the card text
      htmltools::tags$div(
        class = "card-text",
        "Find places where your dollars go the farthest and tips to create amazing travel experiences without breaking the bank. Travel more and spend less!",
        class = "title",
            style = "text-align: center;"))
    )
)

# Render the slideshow
htmltools::browsable(
  tags$html(
    tags$head(
      # Use Bootstrap 5
      tags$link(
        rel = "stylesheet",
        href = "https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
      )
    ),
    
    tags$body(
      slideshow(mission_vision_card),
      # Add some custom CSS for the animations
      card_animation()
    )
  )
)
```


```{r, echo=FALSE}
bslib::card(
  card_header(
    htmltools::tags$p(
    "Deals",
    class = "title",
    style = "font-weight: bold;"
  )),
  style = "border: none; background-color: rgba(246, 215, 176, 0)"
)

# Create a tab panels with cards for services offered
navset_card_tab(
  full_screen = FALSE,

  # game drives
  nav_panel(
    title = "Game drives",
    
      card_header(
        style = "border: 0px;",
        # Add an img tag for the card image
        class = "card-header",
        htmltools::tags$p(
          "The thrill of a game drive with Canary ToursKE"
        )),
    
        card_body(
          # Add a div tag for the card text
          htmltools::tags$div(
            class = "container",
            htmltools::tags$image(
            src = "/pages/images/image3.jpg",
            class = "card-image"
          )),
      
          htmltools::tags$div(
            class = "top-left",
            htmltools::tags$p(
            "As the sun rises over the vast plains, game drive enthusiasts embark on their safari vehicles, accompanied by experienced guides and trackers. The open-sided 4x4 vehicles provide an unobstructed view of the surrounding landscapes, ensuring that every moment is captured, from the majestic elephants grazing in the distance to the elusive big cats prowling through the grass"))
  ),
  
  layout_column_wrap(
    width = 1/2,
    
    card_body(
      htmltools::tags$button(
        class = "button",
        style = "border-top: 0px; border-left: 0px; border-right: 0px;",
        htmltools::tags$a(
        href = " ",
        "Past Events",
        style = "color: inverse;"
        ))),
    
    card_body(
      htmltools::tags$button(
        class = "button",
        style = "border-top: 0px; border-left: 0px; border-right: 0px;",
        htmltools::tags$a(
        href = " ",
        "Future Events",
        style = "color: inverse;"
        ))))),
  
  nav_spacer(),
  
  # Cultural Adventures
  nav_panel(
    "Cultural Adventures",
    
    
      card_header(
        style = "border: 0px;",
        # Add an img tag for the card image
        class = "card-header",
        htmltools::tags$p(
          "Cultural adventures with Canary ToursKE"
        )),
      
      card_body(
          htmltools::tags$div(
            class = "top-left",
            htmltools::tags$p(
            "Kenya, a diverse and vibrant country in East Africa, is home to a rich tapestry of cultural practices that reflect the traditions and values of its numerous ethnic groups. These practices, deeply rooted in history, play a significant role in shaping the identity of the Kenyan people.")),
    
          # Add a div tag for the card text
          htmltools::tags$div(
            class = "container",
            htmltools::tags$image(
            src = "/pages/images/image1.jpg",
            class = "card-image"
          ))),
      
      layout_column_wrap(
    width = 1/2,
    
    card_body(
      htmltools::tags$button(
        class = "button",
        style = "border-top: 0px; border-left: 0px; border-right: 0px;",
        htmltools::tags$a(
        href = " ",
        "Past Events",
        style = "color: inverse;"
        ))),
    
    card_body(
      htmltools::tags$button(
        class = "button",
        style = "border-top: 0px; border-left: 0px; border-right: 0px;",
        htmltools::tags$a(
        href = " ",
        "Future Events",
        style = "color: inverse;"
        ))))),
  
  nav_spacer(),
  
  # Team Building
  nav_panel(
    title = "Team Building",
    
    
      card_header(
        style = "border: 0px;",
        # Add an img tag for the card image
        class = "card-header",
        htmltools::tags$p(
          "Team building with Canary ToursKE"
        )),
    
        card_body(
          # Add a div tag for the card text
          htmltools::tags$div(
            class = "container",
            htmltools::tags$image(
            src = "/pages/images/image5.jpg",
            class = "card-image"
          )),
      
      htmltools::tags$div(
            class = "top-left",
            htmltools::tags$p(
            "work team-building exercises are about feats of human endurance, group problem-solving activities or outdoors pursuits aimed at lifting spirits and fostering a team spirit.(Team Building)"))),
      
      layout_column_wrap(
    width = 1/2,
    
    card_body(
      htmltools::tags$button(
        class = "button",
        style = "border-top: 0px; border-left: 0px; border-right: 0px;",
        htmltools::tags$a(
        href = " ",
        "Past Events",
        style = "color: inverse;"
        ))),
    
    card_body(
      htmltools::tags$button(
        class = "button",
        style = "border-top: 0px; border-left: 0px; border-right: 0px;",
        htmltools::tags$a(
        href = " ",
        "Future Events",
        style = "color: inverse;"
        ))))))

```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Define the cards data
card_images <- function(image_path) {
  src = image_path
  
  list(
    header = "Gallery",
    body1 = card_body(
      # Add a div tag for the card text
          htmltools::tags$div(
            class = "container",
            htmltools::tags$image(
            src = src,
            class = "card-image"
          ))
    ),
    body2 = NULL
  )
}


cards <- lapply(stringr::str_c("./pages/images/", list.files("./pages/images")), function(x) card_images(image_path = x))
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Render the slideshow
htmltools::browsable(
  tags$html(
    tags$head(
      # Use Bootstrap 5
      tags$link(
        rel = "stylesheet",
        href = "https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
      ),
      # Add some custom CSS for the animations
      card_animation()
    ),
    tags$body(
      slideshow(cards)
    )
  )
)
```